<template>
  <Teleport to="body"><div class="fixed inset-0 z-[120] grid place-items-center bg-slate-950/45 p-4 backdrop-blur-sm" @click.self="$emit('close')"><section class="flex max-h-[90dvh] w-full max-w-2xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><header class="flex items-start justify-between border-b border-slate-200 px-5 py-4"><div><p class="text-[10px] font-black uppercase tracking-wider text-fuchsia-600">QuizFlex AI</p><h2 class="mt-1 text-xl font-black text-slate-900">AI nhận xét bộ đề</h2><p class="mt-1 text-xs text-slate-500">AI tự động phân tích toàn bộ câu hỏi và chỉ đưa ra gợi ý.</p></div><button type="button" aria-label="Đóng" class="text-slate-400" @click="$emit('close')"><X class="h-5 w-5" /></button></header><div class="min-h-0 flex-1 overflow-y-auto p-5">
    <div v-if="loading" class="grid min-h-64 place-items-center text-center"><div><LoaderCircle class="mx-auto h-9 w-9 animate-spin text-fuchsia-600" /><p class="mt-3 text-sm font-black">AI đang phân tích toàn bộ bộ đề...</p></div></div>
    <div v-else-if="error" class="rounded-xl border border-rose-200 bg-rose-50 p-5 text-center text-xs font-bold text-rose-700">{{ error }}<br><button class="mt-3 underline" @click="load">Thử lại</button></div>
    <template v-else-if="result"><section class="rounded-xl border border-violet-100 bg-violet-50 p-4"><p class="text-[10px] font-black uppercase tracking-wider text-violet-700">Nhận xét tổng quan</p><div class="mt-2 text-sm leading-6 text-slate-800"><MathText :content="result.summary" /></div></section><section v-if="result.issues.length" class="mt-5"><h3 class="text-xs font-black uppercase tracking-wider text-slate-500">Câu hỏi cần chú ý · {{ result.issues.length }}</h3><div class="mt-2 space-y-2"><button v-for="(issue, index) in result.issues" :key="index" type="button" class="flex w-full gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-left transition hover:border-violet-400 hover:bg-violet-50" @click="goToQuestion(issue)"><TriangleAlert class="mt-0.5 h-4 w-4 shrink-0 text-amber-600" /><span class="min-w-0 flex-1"><b class="text-xs text-slate-900">Câu {{ issue.question_number || questionNumber(issue.question_id) }}</b><span class="mt-1 block text-xs leading-5 text-slate-700"><MathText :content="String(issue.message || '')" compact /></span></span><ChevronRight class="h-4 w-4 shrink-0 text-slate-400" /></button></div></section><section v-if="result.suggestions.length" class="mt-5"><h3 class="text-xs font-black uppercase tracking-wider text-slate-500">Gợi ý chung</h3><div class="mt-2 space-y-2"><div v-for="(item, index) in result.suggestions" :key="index" class="rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-700"><MathText :content="String(item)" /></div></div></section><div v-if="!result.issues.length" class="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">Không phát hiện câu hỏi cần cảnh báo.</div></template>
  </div><footer class="flex justify-end border-t border-slate-200 bg-slate-50 px-5 py-4"><button class="rounded-xl bg-violet-600 px-4 py-2.5 text-xs font-black text-white" @click="$emit('close')">Đóng</button></footer></section></div></Teleport>
</template>
<script setup>
import { onMounted, ref } from 'vue'
import { ChevronRight, LoaderCircle, TriangleAlert, X } from 'lucide-vue-next'
import MathText from '@/components/MathText.vue'
import { reviewWholeQuiz } from '@/services/quiz-editor/quizAiToolsApi.js'
const props = defineProps({ quiz: { type: Object, required: true } })
const emit = defineEmits(['close', 'select-question'])
const loading = ref(false); const error = ref(''); const result = ref(null)
const questionNumber = (id) => Math.max(1, props.quiz.questions.findIndex((q) => String(q.id) === String(id)) + 1)
const goToQuestion = (issue) => { const id = issue.question_id; if (props.quiz.questions.some((q) => String(q.id) === String(id))) emit('select-question', id) }
const load = async () => { if (loading.value) return; loading.value = true; error.value = ''; try { result.value = await reviewWholeQuiz(props.quiz) } catch (e) { error.value = e?.response?.data?.message || 'Không thể phân tích bộ đề lúc này.' } finally { loading.value = false } }
onMounted(load)
</script>
