<template>
  <Teleport to="body"><div class="fixed inset-0 z-[120] grid place-items-center bg-slate-950/45 p-4 backdrop-blur-sm" @click.self="$emit('close')"><section class="flex max-h-[90dvh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><header class="flex items-start justify-between border-b border-slate-200 px-5 py-4"><div><p class="text-[10px] font-black uppercase tracking-wider text-fuchsia-600">QuizFlex AI</p><h2 class="mt-1 text-xl font-black">Tạo câu hỏi tương tự</h2><p class="mt-1 text-xs text-slate-500">Dựa trên {{ sourceQuestions.length }} câu mẫu đã chọn.</p></div><button aria-label="Đóng" @click="$emit('close')"><X class="h-5 w-5" /></button></header><div class="min-h-0 flex-1 overflow-y-auto p-5"><div v-if="loading" class="grid min-h-56 place-items-center text-center"><div><LoaderCircle class="mx-auto h-9 w-9 animate-spin text-fuchsia-600" /><p class="mt-3 text-sm font-black">AI đang tạo câu hỏi tương tự...</p></div></div><div v-else-if="error" class="rounded-xl border border-rose-200 bg-rose-50 p-4 text-xs font-bold text-rose-700">{{ error }} <button class="ml-2 underline" @click="load">Thử lại</button></div><div v-else class="space-y-2"><article v-for="(question, index) in results" :key="question.id" class="flex cursor-pointer gap-3 rounded-xl border p-3" :class="selectedIds.includes(question.id) ? 'border-violet-400 bg-violet-50' : 'border-slate-200'" @click="toggle(question.id)"><input type="checkbox" :checked="selectedIds.includes(question.id)" class="mt-1 accent-violet-600" @click.stop @change="toggle(question.id)"><div class="min-w-0 flex-1"><div class="text-sm font-bold"><MathText :content="question.content" /></div><div class="mt-2 grid gap-1 sm:grid-cols-2"><div v-for="answer in question.answers" :key="answer.id" class="rounded-lg px-2 py-1.5 text-xs" :class="answer.is_correct ? 'bg-emerald-50 text-emerald-800' : 'bg-white text-slate-600'"><MathText :content="answer.content" compact /></div></div></div><span class="text-[10px] font-black text-fuchsia-700">Câu {{ index + 1 }}</span></article></div></div><footer class="flex items-center justify-between border-t border-slate-200 px-5 py-4"><span class="text-xs font-bold text-slate-500">Đã chọn {{ selectedIds.length }} câu</span><div class="flex gap-2"><button class="rounded-xl border px-4 py-2.5 text-xs font-black" @click="$emit('close')">Hủy</button><button class="rounded-xl bg-violet-600 px-4 py-2.5 text-xs font-black text-white disabled:opacity-40" :disabled="!selectedIds.length || loading" @click="apply">Thêm {{ selectedIds.length }} câu</button></div></footer></section></div></Teleport>
</template>
<script setup>
import { onMounted, ref } from 'vue'
import { LoaderCircle, X } from 'lucide-vue-next'
import MathText from '@/components/MathText.vue'
import { generateSimilarQuestions } from '@/services/quiz-editor/quizAiToolsApi.js'
const props = defineProps({ quiz: { type: Object, required: true }, sourceQuestions: { type: Array, required: true } })
const emit = defineEmits(['close', 'select'])
const loading = ref(false); const error = ref(''); const results = ref([]); const selectedIds = ref([])
const load = async () => { if (loading.value) return; loading.value = true; error.value = ''; try { results.value = await generateSimilarQuestions(props.quiz, props.sourceQuestions, 3); selectedIds.value = results.value.map((q) => q.id); if (!results.value.length) throw new Error('AI không trả về câu hỏi phù hợp.') } catch (e) { error.value = e?.response?.data?.message || e?.message || 'Không thể tạo câu hỏi tương tự.' } finally { loading.value = false } }
const toggle = (id) => { selectedIds.value = selectedIds.value.includes(id) ? selectedIds.value.filter((item) => item !== id) : [...selectedIds.value, id] }
const apply = () => emit('select', results.value.filter((q) => selectedIds.value.includes(q.id)).map((q) => ({ ...q, source_type: 'ai' })))
onMounted(load)
</script>
