<template>
  <section class="grid gap-6 py-8 xl:grid-cols-[minmax(0,1fr)_360px]">
    <article class="relative overflow-hidden rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-5 shadow-[var(--shadow-soft)] backdrop-blur-2xl sm:p-8">
      <div class="pointer-events-none absolute -left-24 -top-24 h-80 w-80 rounded-full bg-[var(--primary)]/20 blur-3xl"></div>
      <div class="pointer-events-none absolute -bottom-24 right-0 h-80 w-80 rounded-full bg-[var(--accent)]/10 blur-3xl"></div>
      <div class="relative z-10">
        <div class="mb-7 flex flex-wrap items-center justify-between gap-4">
          <div>
            <div class="mb-4 flex flex-wrap items-center gap-2"><span class="rounded-full border border-[var(--border-strong)] bg-[var(--chip-active)] px-4 py-2 text-xs font-black uppercase tracking-[0.18em] text-[var(--primary)]">Câu {{ currentIndex + 1 }} / {{ quizQuestions.length }}</span><span class="rounded-full border border-[var(--border)] bg-[var(--surface-soft)] px-4 py-2 text-xs font-black text-[var(--muted)]">{{ currentQuestion.category }}</span><span class="rounded-full border border-[var(--border)] bg-[var(--surface-soft)] px-4 py-2 text-xs font-black text-[var(--muted)]">{{ currentQuestion.difficulty }}</span></div>
            <h1 class="max-w-4xl text-3xl font-black leading-tight tracking-[-0.055em] text-[var(--text)] sm:text-5xl">{{ currentQuestion.question }}</h1>
            <p class="mt-4 max-w-2xl text-sm font-medium leading-7 text-[var(--muted)]">Chọn một đáp án đúng nhất. Sau khi trả lời, bạn có thể chuyển sang câu tiếp theo.</p>
          </div>
          <div class="grid gap-3"><div class="relative grid h-24 w-24 place-items-center rounded-full border border-[var(--border)] bg-[var(--surface-soft)] shadow-[var(--shadow-card)]"><div class="absolute inset-1 rounded-full" :style="progressRingStyle"></div><div class="relative z-10 grid h-16 w-16 place-items-center rounded-full bg-[var(--surface-strong)]"><span class="text-lg font-black text-[var(--text)]">{{ progressPercent }}%</span></div></div><div class="text-center text-xs font-black text-[var(--muted)]">Tiến độ</div></div>
        </div>
        <div class="mb-8 overflow-hidden rounded-full border border-[var(--border)] bg-[var(--surface-soft)] p-1"><div class="h-2 rounded-full bg-gradient-to-r from-[var(--primary)] via-[var(--primary-2)] to-[var(--accent)] transition-all duration-500" :style="{ width: `${progressPercent}%` }"></div></div>
        <div class="grid gap-4"><button v-for="answer in currentQuestion.answers" :key="answer.key" type="button" class="group relative overflow-hidden rounded-[1.35rem] border p-4 text-left transition duration-300 hover:-translate-y-1 active:scale-[0.99]" :class="getAnswerClass(answer.key)" @click="selectedAnswer = answer.key"><div v-if="selectedAnswer === answer.key" class="absolute inset-0 bg-gradient-to-r from-[var(--primary)]/10 via-[var(--primary-2)]/10 to-[var(--accent)]/10"></div><div class="relative z-10 flex items-center gap-4"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-[var(--primary)] to-[var(--primary-2)] text-sm font-black text-white shadow-[0_14px_30px_rgba(155,44,255,0.24)] transition group-hover:scale-105">{{ answer.key }}</span><span class="font-bold leading-7 text-[var(--text)]">{{ answer.text }}</span><span v-if="selectedAnswer === answer.key" class="ml-auto grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[var(--chip-active)] text-sm font-black text-[var(--primary)]">✓</span></div></button></div>
        <div class="mt-8 flex flex-wrap items-center justify-between gap-3"><button class="btn-ghost disabled:cursor-not-allowed disabled:opacity-50" type="button" :disabled="currentIndex === 0" @click="goPrevious">Câu trước</button><div class="flex flex-wrap items-center gap-3"><span class="text-sm font-bold text-[var(--muted)]">Đã chọn: <b class="text-[var(--primary)]">{{ selectedAnswer || 'Chưa chọn' }}</b></span><button class="group relative inline-flex min-h-12 items-center justify-center overflow-hidden rounded-full bg-gradient-to-br from-[var(--primary)] via-[var(--primary-2)] to-[var(--accent)] px-6 text-sm font-black text-white shadow-[0_18px_38px_rgba(155,44,255,0.28)] transition hover:-translate-y-1 active:scale-95" type="button" @click="goNext"><span class="absolute inset-0 -translate-x-[120%] bg-gradient-to-r from-transparent via-white/35 to-transparent transition duration-700 group-hover:translate-x-[120%]"></span><span class="relative z-10">{{ isLastQuestion ? 'Hoàn thành' : 'Trả lời và tiếp tục' }}</span></button></div></div>
      </div>
    </article>
    <aside class="grid content-start gap-5">
      <article class="relative overflow-hidden rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow-card)] backdrop-blur-2xl"><div class="relative z-10"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-[0.2em] text-[var(--primary)]">Live room</p><h2 class="mt-2 text-2xl font-black tracking-[-0.05em] text-[var(--text)]">Phòng realtime</h2><p class="mt-2 text-sm text-[var(--muted)]">Mã phòng hiện tại</p></div><span class="rounded-full bg-emerald-500/15 px-3 py-1 text-xs font-black text-emerald-400">Online</span></div><div class="mt-5 rounded-[1.5rem] border border-[var(--border-strong)] bg-[var(--chip-active)] p-5 text-center"><p class="text-xs font-black uppercase tracking-[0.22em] text-[var(--muted)]">Room code</p><div class="mt-2 text-4xl font-black tracking-[0.2em] text-[var(--text)]">QZ24</div></div><div class="mt-5 grid grid-cols-2 gap-3"><div class="rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] p-4"><p class="text-xs font-bold text-[var(--muted)]">Người chơi</p><p class="mt-1 text-2xl font-black text-[var(--text)]">{{ players.length }}</p></div><div class="rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] p-4"><p class="text-xs font-bold text-[var(--muted)]">Thời gian</p><p class="mt-1 text-2xl font-black text-[var(--text)]">08:24</p></div></div></div></article>
      <article class="rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow-card)] backdrop-blur-2xl"><p class="text-xs font-black uppercase tracking-[0.2em] text-[var(--primary)]">Leaderboard</p><h2 class="mt-2 text-2xl font-black text-[var(--text)]">Người chơi</h2><div class="mt-5 grid gap-3"><div v-for="(player, index) in sortedPlayers" :key="player.name" class="flex items-center justify-between gap-3 rounded-[1.25rem] border border-[var(--border)] bg-[var(--surface-soft)] p-3 transition hover:-translate-y-0.5 hover:border-[var(--border-strong)] hover:bg-[var(--chip-active)]"><div class="flex items-center gap-3"><div class="grid h-10 w-10 place-items-center rounded-2xl text-sm font-black" :class="getRankClass(index)">#{{ index + 1 }}</div><div><b class="font-black text-[var(--text)]">{{ player.name }}</b><span class="mt-1 block text-xs font-semibold text-[var(--muted)]">{{ player.status }}</span></div></div><span class="rounded-full bg-gradient-to-br from-[var(--primary)] to-[var(--primary-2)] px-3 py-1 text-xs font-black text-white">{{ player.score }}</span></div></div></article>
      <article class="rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow-card)] backdrop-blur-2xl"><p class="text-xs font-black uppercase tracking-[0.2em] text-[var(--primary)]">Question map</p><div class="mt-4 grid grid-cols-5 gap-2"><button v-for="(_, index) in quizQuestions" :key="index" type="button" class="grid h-10 place-items-center rounded-2xl border text-xs font-black transition hover:-translate-y-0.5" :class="getQuestionMapClass(index)" @click="goToQuestion(index)">{{ index + 1 }}</button></div></article>
    </aside>
  </section>
</template>
<script setup>
import { computed, ref } from 'vue'
import { quizQuestions } from '@/data/demoData'
const currentIndex = ref(0)
const selectedAnswers = ref({ 0: 'A' })
const players = [{ name: 'Minh Anh', status: 'Đã trả lời', score: 320 }, { name: 'Quốc Huy', status: 'Đang suy nghĩ', score: 280 }, { name: 'Gia Linh', status: 'Đã trả lời', score: 250 }]
const currentQuestion = computed(() => quizQuestions[currentIndex.value])
const selectedAnswer = computed({ get: () => selectedAnswers.value[currentIndex.value] || '', set: (value) => { selectedAnswers.value = { ...selectedAnswers.value, [currentIndex.value]: value } } })
const progressPercent = computed(() => Math.round(((currentIndex.value + 1) / quizQuestions.length) * 100))
const progressRingStyle = computed(() => ({ background: `conic-gradient(var(--accent-2) 0 ${progressPercent.value}%, var(--surface-soft) ${progressPercent.value}% 100%)` }))
const isLastQuestion = computed(() => currentIndex.value === quizQuestions.length - 1)
const sortedPlayers = computed(() => [...players].sort((a, b) => b.score - a.score))
const getAnswerClass = (key) => selectedAnswer.value === key ? ['border-[var(--border-strong)]', 'bg-[var(--chip-active)]', 'shadow-[0_18px_44px_rgba(155,44,255,0.16)]'] : ['border-[var(--border)]', 'bg-[var(--surface-soft)]', 'hover:border-[var(--border-strong)]', 'hover:bg-[var(--surface)]']
const getRankClass = (i) => i === 0 ? 'bg-amber-500/15 text-amber-400' : i === 1 ? 'bg-slate-400/15 text-slate-300' : 'bg-orange-500/15 text-orange-400'
const getQuestionMapClass = (i) => i === currentIndex.value ? ['border-[var(--border-strong)]', 'bg-[var(--chip-active)]', 'text-[var(--primary)]'] : selectedAnswers.value[i] ? ['border-emerald-500/30', 'bg-emerald-500/10', 'text-emerald-400'] : ['border-[var(--border)]', 'bg-[var(--surface-soft)]', 'text-[var(--muted)]']
const goPrevious = () => { if (currentIndex.value > 0) currentIndex.value -= 1 }
const goNext = () => { if (!isLastQuestion.value) currentIndex.value += 1 }
const goToQuestion = (i) => { currentIndex.value = i }
</script>
